name: Standard Task
description: A standard task or bug fix.
title: 'CIC-[LEAVE_THIS_EMPTY]: ' #  <-- Just the prefix
labels: ['task']
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Describe the task or bug.'
    validations:
      required: true