name: Task
description: A standard, well-defined piece of work or a sub-task of a larger story.
labels: ['task']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the task.
      placeholder: |
        - Describe here the task
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the specific requirements or acceptance criteria for this task.
      placeholder: |
        - Describe here what is required to complete this task
    validations:
      required: false

  - type: textarea
    id: high-level-requirements
    attributes:
      label: High Level Requirements
      description: Describe the overall goal or the business value this task contributes to.
      placeholder: |
        - Describe here the high level requirements for this task
    validations:
      required: false

  - type: textarea
    id: dev-notes
    attributes:
      label: Dev Notes
      description: Any technical details, implementation notes, or potential challenges for the developer.
      placeholder: |
        - Describe here any technical details, implementation notes, or potential challenges for the developer
    validations:
      required: false

  - type: textarea
    id: solution-design
    attributes:
      label: Solution Design
      description: Outline the proposed technical solution. This can include architectural changes, new components, or API endpoints.
      placeholder: |
        - Describe here the proposed technical solution for this task
    validations:
      required: false